using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class CampfireHealthModel
{
    [RealtimeProperty(1, true, true)]
    private int _health;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class CampfireHealthModel : RealtimeModel {
    public int health {
        get {
            return _healthProperty.value;
        }
        set {
            if (_healthProperty.value == value) return;
            _healthProperty.value = value;
            InvalidateReliableLength();
            FireHealthDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(CampfireHealthModel model, T value);
    public event PropertyChangedHandler<int> healthDidChange;
    
    public enum PropertyID : uint {
        Health = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _healthProperty;
    
    #endregion
    
    public CampfireHealthModel() : base(null) {
        _healthProperty = new ReliableProperty<int>(1, _health);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent)
    {
        _healthProperty.UnsubscribeCallback();
    }
    
    private void FireHealthDidChange(int value) {
        try {
            healthDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context)
    {
        var length = 0;
        length += _healthProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _healthProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Health: {
                    changed = _healthProperty.Read(stream, context);
                    if (changed) FireHealthDidChange(health);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _health = health;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
